const DUMMYIMAGE = "dummyimage";
module.exports = {
  ApiManagementMechApiFullColorPink: DUMMYIMAGE,
  AppServicesOverviewIconPattern: DUMMYIMAGE,
  LogoRedHatOpenShiftDatabaseAccessAStandardRgb: DUMMYIMAGE,
  LogoRedHatOpenShiftApiManagementAStandardRgb: DUMMYIMAGE,
  LogoRedHatOpenShiftApplicationServicesAReverseRgb: DUMMYIMAGE,
  LogoRedHatOpenShiftConnectorsBStandardRgb: DUMMYIMAGE,
  LogoRedHatOpenShiftDataScienceAStandardRgb: DUMMYIMAGE,
  LogoRedHatOpenShiftServiceRegistryAStandardRgb: DUMMYIMAGE,
  LogoRedHatOpenShiftStreamsForApacheKafkaAReverseRgb_310x117: DUMMYIMAGE,
  LogoRedHatOpenShiftStreamsForApacheKafkaAReverseRgb: DUMMYIMAGE,
  LogoRedHatOpenShiftStreamsForApacheKafkaAStandardRgbPng: DUMMYIMAGE,
  LogoRedHatOpenShiftStreamsForApacheKafkaAStandardRgbSvg: DUMMYIMAGE,
  LogoRedHatOpenShiftStreamsForApacheKafkaAWhiteRgb: DUMMYIMAGE,
  RhodsMlTechnology: DUMMYIMAGE,
  RhodsVideoPreview: DUMMYIMAGE,
  Videoplaceholder: DUMMYIMAGE,
  IconPlusSolid: DUMMYIMAGE,
  RhLogoWhite: DUMMYIMAGE,
  NotFoundIcon: DUMMYIMAGE,
};
