name: 'coverage'
#on:
#  pull_request:
#    branches:
#      - master
#      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npx jest