name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.6.2 ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run lint
      - run: npm run build

      - name: Generate coverage report
        uses: codecov/codecov-action@v2
        with:
          verbose: true

  release:
    name: Semantic Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: npx semantic-release
