name: Main changed - build, then release and update GH Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: 16.6.2

  release:
    name: Semantic Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 14
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: npx semantic-release

  update-storybook-on-ghpages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.0

      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 16.6.2

      - name: Build storybook
        run: npm run build-storybook -- --quiet --loglevel silent

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-static # The folder the action should deploy.